import React from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft, FileText } from 'lucide-react';

interface Props {
  onBack: () => void;
}

const TermsOfService: React.FC<Props> = ({ onBack }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="max-w-3xl mx-auto py-8"
    >
      <button
        onClick={onBack}
        className="flex items-center gap-2 text-white/40 hover:text-white text-xs uppercase tracking-widest font-bold mb-8 transition-colors"
      >
        <ArrowLeft className="w-4 h-4" /> Back
      </button>

      <div className="flex items-center gap-3 mb-8">
        <div className="w-10 h-10 rounded-xl bg-[#00f0ff]/10 flex items-center justify-center">
          <FileText className="w-5 h-5 text-[#00f0ff]" />
        </div>
        <h1 className="text-3xl md:text-4xl font-black tracking-tight">Terms of Service</h1>
      </div>

      <p className="text-white/30 text-xs uppercase tracking-widest font-bold mb-10">
        Last updated: February 6, 2026
      </p>

      <div className="space-y-8 text-white/60 text-sm leading-relaxed">
        <section>
          <h2 className="text-white text-lg font-bold mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Ratery ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">2. Description of Service</h2>
          <p>
            Ratery is an AI-powered facial perception analysis tool. You upload a photo, and our AI provides an analysis of perceived social signals based on facial features. Results are for entertainment and self-improvement purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">3. Important Disclaimers</h2>
          <p className="mb-3">
            <strong className="text-white/80">AI analysis is not scientific fact.</strong> The scores, metrics, and insights provided by Ratery are generated by an AI model and represent estimated perceptions — not objective truth. Results may vary between scans.
          </p>
          <p className="mb-3">
            <strong className="text-white/80">Not a diagnostic tool.</strong> Ratery is not a medical, psychological, or professional assessment tool. Do not make life decisions based solely on Ratery results.
          </p>
          <p>
            <strong className="text-white/80">Entertainment purpose.</strong> The Service is intended for entertainment and personal insight. Use it responsibly.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">4. User Accounts</h2>
          <p className="mb-3">
            You must sign in with a Google account to use the Service. You are responsible for maintaining the security of your account. You must be at least 16 years old to use the Service.
          </p>
          <p>
            We reserve the right to suspend or terminate accounts that violate these terms.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">5. Acceptable Use</h2>
          <p className="mb-3">You agree NOT to:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>Upload photos of other people without their consent</li>
            <li>Upload photos of minors (under 16)</li>
            <li>Use the Service for harassment, discrimination, or bullying</li>
            <li>Attempt to reverse-engineer, exploit, or abuse the API</li>
            <li>Use automated tools, bots, or scripts to access the Service</li>
            <li>Share or publish someone else's scan results without their permission</li>
          </ul>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">6. Subscriptions and Payments</h2>
          <p className="mb-3">
            Ratery offers free and paid subscription plans. Paid plans are billed monthly or annually through our payment provider, Creem.io.
          </p>
          <p className="mb-3">
            <strong className="text-white/80">Free plan:</strong> 1 scan total, limited DNA markers.
          </p>
          <p className="mb-3">
            <strong className="text-white/80">Premium plan:</strong> 49 scans per month, additional DNA markers.
          </p>
          <p className="mb-3">
            <strong className="text-white/80">Pro plan:</strong> Unlimited scans, all DNA markers.
          </p>
          <p>
            Scan credits reset monthly. Unused credits do not carry over. Refund policies are subject to the payment provider's terms.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">7. Intellectual Property</h2>
          <p className="mb-3">
            The Ratery brand, interface, algorithms, and content are owned by us. You retain ownership of photos you upload. By using the Service, you grant us a temporary, limited license to process your photo for analysis only.
          </p>
          <p>
            Scan results generated by the AI are provided to you for personal use. You may share your own results but may not claim they represent scientific or professional assessments.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">8. Limitation of Liability</h2>
          <p>
            The Service is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to emotional distress from analysis results, data loss from browser clearing, or service interruptions. Our maximum liability is limited to the amount you paid for the Service in the preceding 12 months.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">9. Changes to Terms</h2>
          <p>
            We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms. Material changes will be communicated via the website.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">10. Governing Law</h2>
          <p>
            These Terms are governed by applicable law. Any disputes shall be resolved through good-faith negotiation first.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-3">11. Contact</h2>
          <p>
            For questions about these Terms, contact us at: <span className="text-[#00f0ff]">support@ratery.cc</span>
          </p>
        </section>
      </div>
    </motion.div>
  );
};

export default TermsOfService;
